### ISSUE TITLE
Stacked new messages / message date.

### ISSUE THREAD

**Issue by QuentinMcCarthy** [Zerthox/ClearVision#89]
I've found on ClearVision Amethyst that the dates for messages and the divider for new messages are stacked on top of each other.

With the BetterDiscord support server I was able to get it fixed by putting a black background on the New Message and Date dividers.

![image](https://user-images.githubusercontent.com/36647653/43694574-162d6d3e-9988-11e8-99e1-fb931053dce3.png)

I mis-clicked close without noticing, ignore the close.

**Comment by OmgDani** [comment]
Fixed hopefully :)

**Comment by QuentinMcCarthy** [comment]
As far as I'm aware, it hasn't been fixed. The issue still appears, however, it seems Discord is inconsistent as to whether or not it does show up. I'm not entirely sure what causes it.

Another issue has actually appeared in the form of the margins between the date dividers and the text below and above being a little too close. I'm not sure if that's the actual theme, or my eyes playing tricks on me, however.

I do use custom CSS within my own theme file to fix various issues and provide my own spin on the theme, and I also use a few plugins. I can provide a list of both later today, as I can't access my computer at the moment.

**Comment by OmgDani** [comment]
it should no longer show the date divider if there is a new message divider and then when the new message divider goes the date should show

**Comment by QuentinMcCarthy** [comment]
Yeah, I noticed that was happening now. Bit weird to see, but at least its fixed the date divider / new message divider overlap.
